# Copyright (C) Nitrokey GmbH
# SPDX-License-Identifier: CC0-1.0

name: Continuous delivery - crates.io

on:
  release:
    types: [published]

jobs:
  publish-trussed-chunked:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.release.tag_name, 'chunked-') }}
    environment: crates.io
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
    - uses: rust-lang/crates-io-auth-action@b7e9a28eded4986ec6b1fa40eeee8f8f165559ec  # v1.0.3
      id: auth
    - run: cargo publish --package trussed-chunked
      env:
        CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
  publish-trussed-fs-info:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.release.tag_name, 'fs-info-') }}
    environment: crates.io
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
    - uses: rust-lang/crates-io-auth-action@b7e9a28eded4986ec6b1fa40eeee8f8f165559ec  # v1.0.3
      id: auth
    - run: cargo publish --package trussed-fs-info
      env:
        CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
  publish-trussed-hkdf:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.release.tag_name, 'hkdf-') }}
    environment: crates.io
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
    - uses: rust-lang/crates-io-auth-action@b7e9a28eded4986ec6b1fa40eeee8f8f165559ec  # v1.0.3
      id: auth
    - run: cargo publish --package trussed-hkdf
      env:
        CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
  publish-trussed-hpke:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.release.tag_name, 'hpke-') }}
    environment: crates.io
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
    - uses: rust-lang/crates-io-auth-action@b7e9a28eded4986ec6b1fa40eeee8f8f165559ec  # v1.0.3
      id: auth
    - run: cargo publish --package trussed-hpke
      env:
        CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
  publish-trussed-manage:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.release.tag_name, 'manage-') }}
    environment: crates.io
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
    - uses: rust-lang/crates-io-auth-action@b7e9a28eded4986ec6b1fa40eeee8f8f165559ec  # v1.0.3
      id: auth
    - run: cargo publish --package trussed-manage
      env:
        CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
  publish-trussed-wrap-key-to-file:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.release.tag_name, 'wrap-key-to-file-') }}
    environment: crates.io
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
    - uses: rust-lang/crates-io-auth-action@b7e9a28eded4986ec6b1fa40eeee8f8f165559ec  # v1.0.3
      id: auth
    - run: cargo publish --package trussed-wrap-key-to-file
      env:
        CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
